export const SAVE_ACCESS_TOKEN = "SAVE_ACCESS_TOKEN";
export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_PLAYLISTS = "FETCH_USER_PLAYLISTS";
export const FETCH_PLAYLIST_SONGS = "FETCH_PLAYLIST_SONGS";
export const UPDATE_LOADING_STATE = "UPDATE_LOADING_STATE";
